### ISSUE TITLE
Numero bin per variabile di un dataset

### ISSUE THREAD

**Issue by jenkin** [Dataninja/advanced-mapping-tool#29]
Al momento il numero di bin per disegnare la choropleth è fissato a livello di dataset, ma all'interno dello stesso dataset possono esserci colonne con ordini di grandezza dei valori molto diversi tra loro e questo può causare classi vuote o ripetute.

Ci sono due strade per risolvere questo problema:
-  permettere all'utente di specificare il numero di bin per ogni colonna (con un valore di default pari a quello associato al dataset;
-  provare a rendere automatico il processo: se il calcolo degli intervalli porta a intervalli ripetuti, si eliminano le ripetizioni e si rifà il calcolo con un numero minore di bin.

Se entrambe le strade sono fattibili, probabilmente la cosa migliore è implementare la prima e ricadere nella seconda se il numero di bin indicato non è buono.

**Comment by nelsonmau** [comment]
qua ci vuole una dritta di san @aborruso

**Comment by aborruso** [comment]
@jenkin @nelsonmau voi andate a martello, io non ce la posso fare
