### ISSUE TITLE
Attibution line > Icons & credits

### ISSUE THREAD

**Issue by nelsonmau** [Dataninja/advanced-mapping-tool#34]
Position: .conf.js > Attibution Line

Icons doesn't come from "Freepik / Simple Share" as follow:

<code>'icons from <a href="http://www.flaticon.com/" target="_blank">Freepik</a> and <a href="http://www.simplesharebuttons.com/" target="_blank">Simple Share Buttons</a>'
</code>
The previous attribution would be removed

**Comment by jenkin** [comment]
For now, that attribution is correct because of the origin of default images in icons/ folder... if you don't want to use that images, don't use them and change that line as you want! :)
